# Generated by Django 3.0.5 on 2021-02-27 09:43

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('reviews', models.TextField()),
                ('quotes', models.TextField()),
            ],
        ),
    ]
